=== matanlurey/tts-save-format/SaveState.json
{
  "$id": "https://tts.swlegion.dev/SaveState.json",
  "$schema": "http://json-schema.org/draft-07/schema",

  "title": "SaveState",
  "type": "object",

  "properties": {
    "SaveName": {
      "type": "string",
      "default": ""
    },

    "GameMode": {
      "type": "string",
      "default": ""
    },

    "Gravity": {
      "type": "number",
      "default": 0.5
    },

    "PlayArea": {
      "type": "number",
      "default": 0.5
    },

    "Date": {
      "type": "string",
      "default": ""
    },

    "Table": {
      "type": "string",
      "default": ""
    },

    "TableURL": {
      "type": ["string", "null"],
      "default": null,
      "description": "URL or empty string"
    },

    "Sky": {
      "type": "string",
      "default": ""
    },

    "SkyURL": {
      "type": ["string", "null"],
      "default": null,
      "description": "URL or empty string"
    },

    "Note": {
      "type": "string",
      "default": ""
    },

    "Rules": {
      "type": "string",
      "default": ""
    },

    "XmlUI": {
      "type": "string",
      "default": ""
    },

    "CustomUIAssets": {
      "type": "array",
      "items": {
        "$ref": "./CustomAssetState.json"
      }
    },

    "LuaScript": {
      "type": "string",
      "default": ""
    },

    "LuaScriptState": {
      "type": "string",
      "default": ""
    },

    "Grid": {
      "$ref": "./GridState.json",
      "description": "Grid menu settings."
    },

    "Lighting": {
      "$ref": "./LightingState.json",
      "description": "Lighting menu settings."
    },

    "Hands": {
      "$ref": "./HandsState.json",
      "description": "Hand menu settings and hand positions."
    },

    "Turns": {
      "$ref": "./TurnsState.json",
      "description": "Turn menu settings."
    },

    "VectorLines": {
      "type": "array",
      "items": {
        "$ref": "./VectorLineState.json"
      },
      "description": "Vector lines on canvas 0 (table + beyond)."
    },

    "ObjectStates": {
      "type": "array",
      "items": {
        "$ref": "./ObjectState.json"
      },
      "description": "Objects on the table."
    },

    "SnapPoints": {
      "type": "array",
      "items": {
        "$ref": "./SnapPointState.json"
      },
      "description": "Snap points not attached to objects."
    },

    "DecalPallet": {
      "type": "array",
      "items": {
        "$ref": "./CustomDecalState.json"
      },
      "description": "Decals that can be placed in the world."
    },

    "Decals": {
      "type": "array",
      "items": {
        "$ref": "./DecalState.json"
      },
      "description": "Decals not attached to objects."
    },

    "TabStates": {
      "type": "object",
      "additionalProperties": {
        "$ref": "./TabState.json"
      },
      "description": "Notepad tabs"
    },

    "CameraStates": {
      "type": "array",
      "items": {
        "anyOf": [{ "$ref": "./CameraState.json" }, { "type": "null" }]
      },
      "description": "Saved camera positions."
    },

    "VersionNumber": {
      "type": "string",
      "default": ""
    },

    "MusicPlayer": {}
  },

  "additionalProperties": false,

  "required": [
    "SaveName",
    "GameMode",
    "Gravity",
    "PlayArea",
    "Date",
    "Table",
    "Sky",
    "Rules",
    "XmlUI",
    "LuaScript",
    "LuaScriptState",
    "Grid",
    "Lighting",
    "Hands",
    "Turns",
    "ObjectStates",
    "DecalPallet",
    "TabStates",
    "VersionNumber"
  ]
}

=== matanlurey/tts-save-format/test/saves/sample.json
{
  "SaveName": "Stardust",
  "GameMode": "Stardust",
  "Gravity": 0.5,
  "PlayArea": 0.5,
  "Date": "4/4/2020 6:01:57 PM",
  "Table": "Table_RPG",
  "Sky": "Sky_Forest",
  "Note": "",
  "Rules": "",
  "LuaScriptState": "",
  "Grid": {
    "Type": 0,
    "Lines": false,
    "Color": {
      "r": 0,
      "g": 0,
      "b": 0
    },
    "Opacity": 0.75,
    "ThickLines": false,
    "Snapping": false,
    "Offset": false,
    "BothSnapping": false,
    "xSize": 2,
    "ySize": 2,
    "PosOffset": {
      "x": 0,
      "y": 1,
      "z": 0
    }
  },
  "Lighting": {
    "LightIntensity": 0.54,
    "LightColor": {
      "r": 1,
      "g": 0.9804,
      "b": 0.8902
    },
    "AmbientIntensity": 1.3,
    "AmbientType": 0,
    "AmbientSkyColor": {
      "r": 0.5,
      "g": 0.5,
      "b": 0.5
    },
    "AmbientEquatorColor": {
      "r": 0.5,
      "g": 0.5,
      "b": 0.5
    },
    "AmbientGroundColor": {
      "r": 0.5,
      "g": 0.5,
      "b": 0.5
    },
    "ReflectionIntensity": 1,
    "LutIndex": 0,
    "LutContribution": 1
  },
  "Hands": {
    "Enable": true,
    "DisableUnused": false,
    "Hiding": 0,
    "HandTransforms": [
      {
        "Color": "Red",
        "Transform": {
          "posX": -15.1108065,
          "posY": 4.862885,
          "posZ": -20.1076221,
          "rotX": 0,
          "rotY": 0,
          "rotZ": 0,
          "scaleX": 11.7727613,
          "scaleY": 9.174497,
          "scaleZ": 4.87123871
        }
      },
      {
        "Color": "Yellow",
        "Transform": {
          "posX": -30.2150211,
          "posY": 4.862885,
          "posZ": 10.17524,
          "rotX": 0,
          "rotY": 90,
          "rotZ": 0,
          "scaleX": 11.6606913,
          "scaleY": 9.174497,
          "scaleZ": 4.922907
        }
      },
      {
        "Color": "Purple",
        "Transform": {
          "posX": 30.25128,
          "posY": 4.862885,
          "posZ": 9.59069252,
          "rotX": 0,
          "rotY": 270,
          "rotZ": 0,
          "scaleX": 11.6606846,
          "scaleY": 9.174497,
          "scaleZ": 4.922907
        }
      },
      {
        "Color": "Blue",
        "Transform": {
          "posX": 15.4749184,
          "posY": 4.862885,
          "posZ": 19.8365288,
          "rotX": 0,
          "rotY": 179.8,
          "rotZ": 0,
          "scaleX": 11.7779245,
          "scaleY": 9.174497,
          "scaleZ": 4.87446
        }
      },
      {
        "Color": "White",
        "Transform": {
          "posX": 15.1961479,
          "posY": 4.862885,
          "posZ": -20.1400986,
          "rotX": 0,
          "rotY": 0,
          "rotZ": 0,
          "scaleX": 11.7727489,
          "scaleY": 9.17449951,
          "scaleZ": 4.87123871
        }
      },
      {
        "Color": "Green",
        "Transform": {
          "posX": -15.1927767,
          "posY": 4.862885,
          "posZ": 19.787817,
          "rotX": 0,
          "rotY": 180,
          "rotZ": 0,
          "scaleX": 11.7727489,
          "scaleY": 9.174497,
          "scaleZ": 4.87123871
        }
      },
      {
        "Color": "Pink",
        "Transform": {
          "posX": 30.10358,
          "posY": 4.862885,
          "posZ": -8.449126,
          "rotX": 0,
          "rotY": 270,
          "rotZ": 0,
          "scaleX": 11.6606808,
          "scaleY": 9.174497,
          "scaleZ": 4.922907
        }
      },
      {
        "Color": "Orange",
        "Transform": {
          "posX": -30.247818,
          "posY": 4.862885,
          "posZ": -8.822588,
          "rotX": 0,
          "rotY": 90,
          "rotZ": 0,
          "scaleX": 11.6606951,
          "scaleY": 9.174497,
          "scaleZ": 4.922907
        }
      }
    ]
  },
  "Turns": {
    "Enable": false,
    "Type": 0,
    "TurnOrder": [],
    "Reverse": false,
    "SkipEmpty": false,
    "DisableInteractions": false,
    "PassTurns": true,
    "TurnColor": ""
  },
  "DecalPallet": [],
  "TabStates": {
    "0": {
      "title": "Rules",
      "body": "",
      "color": "Grey",
      "visibleColor": {
        "r": 0.5,
        "g": 0.5,
        "b": 0.5
      },
      "id": 0
    },
    "1": {
      "title": "White",
      "body": "",
      "color": "White",
      "visibleColor": {
        "r": 1,
        "g": 1,
        "b": 1
      },
      "id": 1
    },
    "2": {
      "title": "Brown",
      "body": "",
      "color": "Brown",
      "visibleColor": {
        "r": 0.443,
        "g": 0.231,
        "b": 0.09
      },
      "id": 2
    },
    "3": {
      "title": "Red",
      "body": "",
      "color": "Red",
      "visibleColor": {
        "r": 0.856,
        "g": 0.1,
        "b": 0.094
      },
      "id": 3
    },
    "4": {
      "title": "Orange",
      "body": "",
      "color": "Orange",
      "visibleColor": {
        "r": 0.956,
        "g": 0.392,
        "b": 0.113
      },
      "id": 4
    },
    "5": {
      "title": "Yellow",
      "body": "",
      "color": "Yellow",
      "visibleColor": {
        "r": 0.905,
        "g": 0.898,
        "b": 0.172
      },
      "id": 5
    },
    "6": {
      "title": "Green",
      "body": "",
      "color": "Green",
      "visibleColor": {
        "r": 0.192,
        "g": 0.701,
        "b": 0.168
      },
      "id": 6
    },
    "7": {
      "title": "Blue",
      "body": "",
      "color": "Blue",
      "visibleColor": {
        "r": 0.118,
        "g": 0.53,
        "b": 1
      },
      "id": 7
    },
    "8": {
      "title": "Teal",
      "body": "",
      "color": "Teal",
      "visibleColor": {
        "r": 0.129,
        "g": 0.694,
        "b": 0.607
      },
      "id": 8
    },
    "9": {
      "title": "Purple",
      "body": "",
      "color": "Purple",
      "visibleColor": {
        "r": 0.627,
        "g": 0.125,
        "b": 0.941
      },
      "id": 9
    },
    "10": {
      "title": "Pink",
      "body": "",
      "color": "Pink",
      "visibleColor": {
        "r": 0.96,
        "g": 0.439,
        "b": 0.807
      },
      "id": 10
    },
    "11": {
      "title": "Black",
      "body": "",
      "color": "Black",
      "visibleColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.25
      },
      "id": 11
    }
  },
  "VersionNumber": "v12.3.3",
  "ObjectStates": [
    {
      "Name": "BlockSquare",
      "Transform": {
        "posX": -17.1639633,
        "posY": 1.45999992,
        "posZ": 7.31388664,
        "rotX": -8.647808e-7,
        "rotY": 1.39818837e-7,
        "rotZ": 8.177796e-7,
        "scaleX": 1,
        "scaleY": 1,
        "scaleZ": 1
      },
      "Nickname": "Red Block",
      "Description": "",
      "GMNotes": "",
      "ColorDiffuse": {
        "r": 0.9264706,
        "g": 0,
        "b": 0
      },
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "LuaScriptState": "",
      "GUID": "f3c00b",
      "ContainedObjects": [],
      "LuaScript": "",
      "XmlUI": ""
    },
    {
      "Name": "Bag",
      "Transform": {
        "posX": -11.4274111,
        "posY": 0.7749659,
        "posZ": 3.57388115,
        "rotX": 0.000004265533,
        "rotY": -4.93587663e-7,
        "rotZ": 0.00000431555873,
        "scaleX": 1,
        "scaleY": 1,
        "scaleZ": 1
      },
      "Nickname": "Bag of Stuff",
      "Description": "",
      "GMNotes": "",
      "ColorDiffuse": {
        "r": 0.7058823,
        "g": 0.366520882,
        "b": 0
      },
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "MaterialIndex": -1,
      "MeshIndex": -1,
      "LuaScriptState": "",
      "GUID": "4dccf2",
      "ContainedObjects": [
        {
          "Name": "BlockTriangle",
          "Transform": {
            "posX": -11.4116583,
            "posY": 3.25869536,
            "posZ": 3.435723,
            "rotX": 359.0296,
            "rotY": 0.00106706074,
            "rotZ": 359.8792,
            "scaleX": 1,
            "scaleY": 1,
            "scaleZ": 1
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "ColorDiffuse": {
            "r": 0.00539905,
            "g": 0.772058845,
            "b": 0
          },
          "Locked": false,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "LuaScriptState": "",
          "GUID": "3f4a4f",
          "ContainedObjects": [],
          "LuaScript": "",
          "XmlUI": ""
        },
        {
          "Name": "BlockRectangle",
          "Transform": {
            "posX": -11.3804674,
            "posY": 3.54467678,
            "posZ": 3.70477486,
            "rotX": 0.373311281,
            "rotY": -0.0009935839,
            "rotZ": 359.695,
            "scaleX": 1,
            "scaleY": 1,
            "scaleZ": 1
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "ColorDiffuse": {
            "r": 0,
            "g": 0.201567829,
            "b": 0.8235294
          },
          "Locked": false,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "LuaScriptState": "",
          "GUID": "b60aa6",
          "ContainedObjects": [],
          "LuaScript": "",
          "XmlUI": ""
        }
      ],
      "LuaScript": "",
      "XmlUI": ""
    },
    {
